#!/bin/bash

brightness=30
if [ -f /tmp/oled_brightness ]; then
 read brightness < /tmp/oled_brightness
fi

brightness2=0
if [ -f /tmp/oled_brightness2 ]; then
 read brightness2 < /tmp/oled_brightness2
fi

gamma=6
if [ -f /tmp/oled_gamma ]; then
 read gamma < /tmp/oled_gamma
fi

gamma2=$gamma
if [ -f /tmp/oled_gamma2 ]; then
 read gamma2 < /tmp/oled_gamma2
fi

echo $brightness  > /tmp/oled_brightness2
echo $brightness2 > /tmp/oled_brightness
echo $gamma       > /tmp/oled_gamma2
echo $gamma2      > /tmp/oled_gamma

oled_set
