#!/bin/bash

brightness=30
if [ -f /tmp/oled_brightness ]; then
 read brightness < /tmp/oled_brightness
fi

if [ $brightness -lt 30 ]; then
 brightness=$((brightness+1))
fi

echo $brightness > /tmp/oled_brightness

oled_set
