#!/bin/bash

brightness=30
if [ -f /tmp/oled_brightness ]; then
 read brightness < /tmp/oled_brightness
fi

if [ $brightness -ge 2 ]; then
 timeout=300
else
 if [ $brightness -ge 1 ]; then
  timeout=30
 else
  if [ $brightness -ge 0 ]; then
   timeout=5
  else
   timeout=1
   brightness=0
  fi
 fi
fi

gamma=6
if [ -f /tmp/oled_gamma ]; then
 read gamma < /tmp/oled_gamma
fi

temperature=6500
if [ -f /tmp/oled_temperature ]; then
 read temperature < /tmp/oled_temperature
fi

status=$(xset q | grep "Monitor is")
if [[ "$status" == *"On"* ]]; then
 was_on=1
else
#was_on=0
 was_on=1
fi

xset dpms force on

if (( was_on = 0 )); then
 sleep 0.6
fi

redshift -m vidmode -P -O $temperature -b `echo "e(l(0.1)*(30-$brightness)/30 )" | bc -l` -P -g `echo "$gamma/20+0.7" | bc -l`

xset dpms s $timeout
