#!/bin/bash

brightness=30
if [ -f /tmp/oled_brightness ]; then
 read brightness < /tmp/oled_brightness
fi

gamma=6
if [ -f /tmp/oled_gamma ]; then
 read gamma < /tmp/oled_gamma
fi

temperature=6500
if [ -f /tmp/oled_temperature ]; then
 read temperature < /tmp/oled_temperature
fi

saturation=10
if [ -f /tmp/oled_saturation ]; then
 read saturation < /tmp/oled_saturation
fi

echo
printf " Brightness %.2f\n" `echo "e(l(0.1)*(30-$brightness)/30 )" | bc -l`
printf "      Gamma %.2f\n" `echo "$gamma/20+0.7" | bc -l`
printf " Saturation %.2f\n" `echo "$saturation/10" | bc -l`
printf "Temperature %dK\n"  $temperature
echo
